name: suricata

services:
  suricate:
    container_name: "suricata"
    build:
      context: "containers/suricata"
      args:
        BASE_IMAGE: "jasonish/suricata:latest"
    network_mode: "host"
    volumes:
        - type: "bind"
          source: "./mounts/suricata/logs"
          target: "/var/log/suricata"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    command: /docker-entrypoint.sh -i ${INTERFACE}
