name: suricata

services:
  suricata:
    container_name: "suricata"
    build:
      context: "containers/suricata"
    network_mode: "host"
#    volumes:
#        - type: "bind"
#          source: "./mounts/suricata/logs"
#          target: "/var/log/suricata"
    command: /docker-entrypoint.sh -i ${INTERFACE}
