name: suricata

services:
  suricata:
    container_name: "suricata"
    build:
      context: "containers/suricata"
    network_mode: "host"
#    volumes:
#        - type: "bind"
#          source: "./mounts/suricata/logs"
#          target: "/var/log/suricata"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
      - SYS_ADMIN
      - CHOWN
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
      - FOWNER
    # depends_on:
    #   syslog:
    #     condition: service_healthy
    #     restart: true
    command: /docker-entrypoint.sh -i ${INTERFACE}

  syslog:
    container_name: "syslog"
    build:
      context: "containers/syslog-ng"
    ports:
      - 514:5514/udp
      - 601:6601/tcp
      - 6514:6514/tcp
    restart: unless-stopped
