name: suricata

services:
  suricata:
    container_name: "suricata"
    build:
      context: "containers/"
      target: suricata
    network_mode: "host"
    command: /docker-entrypoint.sh -i ${INTERFACE}

  testserver:
    container_name: "testserver"
    build:
      context: "containers/"
      target: testserver
    ports:
      - 9999:9999/tcp